### PR TITLE
storage configuration

### LINKED ISSUE #1: A user can specify a folder as the data storage location.

### LINKED ISSUE #138: settings file
so user can save e.g. their theme changes

### LINKED ISSUE #186: Missing MUST HAVE feature: specify folder
The ability to specify a specific folder as the data storage location. With this feature, Jim can choose to store the data file in a local folder controlled by a cloud syncing service (e.g. dropbox), allowing him to access task data from multiple computers.

### PR DESCRIPTION
**Pull request by 9gix**
This closes #138, closes #1, closes #186

### CODE REVIEW

**Comment by 9gix** [comment]
@eatedcookie How's the GUI for configuring the storage location?

**Comment by bsmmoon** [comment]
Now that the DB location can change, the DB should be saved on the exit command as well. I changed the directory and restarted the program, and my to-do list is gone.

**Comment by bsmmoon** [comment]
Then I changed the directory back to the original dir. The previous to-do list is completely cleaned. :o

**Comment by bsmmoon** [comment]
1. Have a to-do list at the default directory.
2. Change directory.
3. Restart ~ a new calendar is loaded
4. Change directory back into the default directory.
5. Add a task.
6. Restart ~ the original calendar is overwritten and there is only the task that I just added.

**Comment by bsmmoon** [comment]
Suggestion:
When the directory is changed, the new directory should contain a copy of the original calendar RIGHT AFTER THE DIRECTORY CHANGES.

**Comment by 9gix** [comment]
That's not the expected behavior.
Changing directory back should not destroy the task. the task will only be destroy if the calendar file is corrupted.

**Comment by 9gix** [comment]
@bsmmoon I can't replicate the issues you mentioned

**Pull request merged**
