### PR TITLE
setup documentation page

### PR DESCRIPTION
**Pull request by 9gix**
- [x] Setup [Doxygen configuration file](https://github.com/cs2103aug2015-w11-2c/DoLah/blob/feature/api-docs/Doxyfile)
- [x] Setup Github [Documentation Page](http://cs2103aug2015-w11-2c.github.io/docs/)

### CODE REVIEW

**Comment by starkipraggy** [comment]
Good to go

**Comment by 9gix** [comment]
To keep our PR list clean, I will close this PR because no one is interested in Merging it. Consider Re-open it if you decided to do so. :disappointed:

**Comment by bsmmoon** [comment]
oops keep forgetting about this one.. sorry ah.

I approve :+1: Shall we reopen and proceed?

**Comment by 9gix** [comment]
I'm tired fixing outdated conflict.

**Comment by 9gix** [comment]
Due to inconsistency in the local master branch of @starkipraggy

**Pull request closed without merging**
