### PR TITLE
CommandTokenizer

### LINKED ISSUE #20: Create Command Parser
CommandParser
- [ ] parse

CommandTokenizer
- [ ] findCommand
- [ ] findTags
- [ ] findDate
- [ ] findDescription
- [ ] findPriority

TokenizerLibrary.cpp
- [x] explode
- [x] vectorToString
- [x] tolowercase
- [x] inArray

### PR DESCRIPTION
**Pull request by bsmmoon**
This closes #20 

CommandTokenizer
- [ ] tokenize
- [x] findCommand
- [x] findTags
- [ ] findDate
- [x] findDescription
- [ ] findPriority

TokenizerLibrary.cpp
- [x] explode
- [x] vectorToString
- [x] tolowercase
- [x] inArray

IToken Objects
- [x] ITokenObject
- [x] DateTimeToken
- [x] StringToken
- [x] IntegerToken

### CODE REVIEW

**Comment by 9gix** [comment]
@bsmmoon please update the class diagram in our project shared drive, so that all of us could understand how you design the tokenizer.

**Comment by bsmmoon** [comment]
@9gix I updated at class diagram (Eugene) alrdy. I just used yours bc my thing is quite behind.

**Comment by bsmmoon** [comment]
and don't want manual conflict resolution.....

**Comment by bsmmoon** [comment]
@9gix BTW I am not sure whether I am doing the polymorphism right or not. Plz share me some advice later.

**Comment by 9gix** [comment]
@bsmmoon So with the updated system design, do we still need this PR? shall we close this PR?

**Comment by bsmmoon** [comment]
@9gix Part of the list will be pruned and the rest will now belong to parser #20 .

**Comment by 9gix** [comment]
@bsmmoon consider deleting this branch

**Comment by bsmmoon** [comment]
agreed

**Pull request closed without merging**
