### PR TITLE
Feature/parser

### LINKED ISSUE #20: Create Command Parser
CommandParser
- [ ] parse

CommandTokenizer
- [ ] findCommand
- [ ] findTags
- [ ] findDate
- [ ] findDescription
- [ ] findPriority

TokenizerLibrary.cpp
- [x] explode
- [x] vectorToString
- [x] tolowercase
- [x] inArray

### PR DESCRIPTION
**Pull request by bsmmoon**
This closes #20 

CommandParser
- [x] parse
- [x] parseAdd
- [x] parseSearch
- [x] parseEdit
- [x] parseDelete
- [x] parseClear
- [x] parseUndo

CommandTokenizer
- [x] findCommand
- [x] findTags
- [x] findDate
- [x] findDescription

It closes #55 , #60 , #54 , #72

### CODE REVIEW

**Comment by bsmmoon** [comment]
note: Task time attributes are changed into std::tm class.

**Comment by 9gix** [comment]
Pls don't merge this branch first. Build error.

**Comment by bsmmoon** [comment]
@9gix I merged with master and handled the errors, so this branch version is building. Do you think it will help?

**Comment by 9gix** [comment]
:+1:

**Comment by starkipraggy** [comment]
Reviewed the code. Event Task is still outstanding. However the parser is working and that's what's important.

**Pull request merged**
