### PR TITLE
Initial commit for undoredo

### LINKED ISSUE #4: A user can undo their action

### LINKED ISSUE #32: Implement Undo Functionality

### LINKED ISSUE #36: Implement Redo Functionality

### PR DESCRIPTION
**Pull request by starkipraggy**
Closes #4, closes #32, closes #36.

- [x] Undo functionality
- [x] Redo functionality

### CODE REVIEW

**Comment by bsmmoon** [comment]
After search undo does nothing. Bug fix can be done for v0.5.

**Comment by bsmmoon** [comment]
redo
redo <- crash

undo
undo <- crash

1
2
undo
redo <- 2 2 instead of 1 2 (generally redo seems to be queue not stack)

**Comment by bsmmoon** [comment]
...Your `undo` removes the bottom of the list and `redo` copies the top of the list.

wow

**Comment by bsmmoon** [comment]
It has so much random behaviours that I cannot even catch them all....

**Comment by 9gix** [comment]
@bsmmoon @starkipraggy consider deleting this branch?

**Pull request merged**
